table Dim_Calendario
	lineageTag: 61078c2a-60a6-4b51-aac9-cc8a0394fffc

	column Fecha
		dataType: dateTime
		formatString: Long Date
		lineageTag: 81b55687-750c-4faa-89c2-1ca0ac3542db
		summarizeBy: none
		sourceColumn: Fecha

		variation Variación
			isDefault
			relationship: ce77da56-2e2d-4ff9-a2ac-dc344bd0fa5d
			defaultHierarchy: LocalDateTable_fad4a30f-0d1a-4624-9c83-308ff9c18e47.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Año
		dataType: int64
		formatString: 0
		lineageTag: 9d7fe42a-991a-4605-af3f-7c1fc2a3de14
		summarizeBy: sum
		sourceColumn: Año

		annotation SummarizationSetBy = Automatic

	column Semana
		dataType: int64
		formatString: 0
		lineageTag: 8ee725f7-9f80-40ec-856b-bb8b70237bf2
		summarizeBy: sum
		sourceColumn: Semana

		annotation SummarizationSetBy = Automatic

	column Mes
		dataType: string
		lineageTag: f16d169d-4eb5-4a0f-9143-851b1ce6b72c
		summarizeBy: none
		sourceColumn: Mes

		annotation SummarizationSetBy = Automatic

	column 'Numero Mes'
		dataType: int64
		formatString: 0
		lineageTag: 9dcfafd1-e166-4d3f-a1de-c391d209617e
		summarizeBy: sum
		sourceColumn: Numero Mes

		annotation SummarizationSetBy = Automatic

	column datekey
		dataType: int64
		formatString: 0
		lineageTag: 41af39cc-8b4d-43a0-94e5-62be6b1d4e44
		summarizeBy: none
		sourceColumn: datekey

		annotation SummarizationSetBy = Automatic

	column MesAño = FORMAT('Dim_Calendario'[Fecha], "MMM yyyy")
		lineageTag: 5a4b3bb0-f1d7-47bc-b507-a60314217edc
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column OrdenMesAño = YEAR('Dim_Calendario'[Fecha]) * 100 + MONTH('Dim_Calendario'[Fecha])
		formatString: 0
		lineageTag: 0b76602d-69bb-4f6b-99af-fafa45a373f5
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition Dim_Calendario = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\arife\Downloads\VentasVehiculos.xlsx"), null, true),
				    Dim_Calendario_Table = Origen{[Item="Dim_Calendario",Kind="Table"]}[Data],
				    #"Tipo cambiado" = Table.TransformColumnTypes(Dim_Calendario_Table,{{"Fecha", type date}, {"Año", Int64.Type}, {"Semana", Int64.Type}, {"Mes", type text}, {"Numero Mes", Int64.Type}, {"datekey", Int64.Type}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table

