table Fotos_Vehiculos
	lineageTag: e663b404-0f5f-42d5-a616-816559ae89dd

	column Id
		dataType: int64
		formatString: 0
		lineageTag: 5f42adb9-3df9-4637-9faf-1cfa98729d44
		summarizeBy: none
		sourceColumn: Id

		annotation SummarizationSetBy = Automatic

	column Modelo
		dataType: string
		lineageTag: 9c8b20e3-77b9-4314-af70-da9564f6cf6e
		summarizeBy: none
		sourceColumn: Modelo

		annotation SummarizationSetBy = Automatic

	column Version
		dataType: string
		lineageTag: 8eadae1b-5a99-4318-8cd6-5cf96892fdf4
		summarizeBy: none
		sourceColumn: Version

		annotation SummarizationSetBy = Automatic

	column Precio
		dataType: int64
		formatString: 0
		lineageTag: eb6bfce9-46a7-48d4-a892-cec957de1deb
		summarizeBy: none
		sourceColumn: Precio

		annotation SummarizationSetBy = Automatic

	column Imagen
		dataType: string
		lineageTag: e6b45c4c-ff4c-4cd3-b8d8-000abbbc479c
		summarizeBy: none
		sourceColumn: Imagen

		annotation SummarizationSetBy = Automatic

	partition Fotos_Vehiculos = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\arife\Downloads\VentasVehiculos.xlsx"), null, true),
				    Fotos_Vehiculos_Table = Origen{[Item="Fotos_Vehiculos",Kind="Table"]}[Data],
				    #"Tipo cambiado" = Table.TransformColumnTypes(Fotos_Vehiculos_Table,{{"Id", Int64.Type}, {"Modelo", type text}, {"Version", type text}, {"Precio", Int64.Type}, {"Imagen", type text}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table

